'messages', 'CREATE TABLE `messages` (\n  `message_id` varchar(36) NOT NULL,\n  `conversation_id` varchar(36) DEFAULT NULL,\n  `user_id` varchar(36) DEFAULT NULL,\n  `user_message` text,\n  `bot_message` text,\n  `timestamp_user` datetime DEFAULT NULL,\n  `timestamp_bot` datetime DEFAULT NULL,\n  PRIMARY KEY (`message_id`),\n  KEY `idx_conversation_id` (`conversation_id`),\n  KEY `idx_user_id` (`user_id`),\n  CONSTRAINT `messages_ibfk_1` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`conversation_id`),\n  CONSTRAINT `messages_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'



'lead_analytics', 'CREATE TABLE `lead_analytics` (\n  `lead_id` varchar(36) NOT NULL,\n  `lead_type` varchar(50) NOT NULL DEFAULT \'appointment_scheduled\',\n  `name` varchar(100) NOT NULL,\n  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n  PRIMARY KEY (`lead_id`),\n  KEY `idx_lead_type` (`lead_type`),\n  KEY `idx_created_at` (`created_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'


'chatbot_close_events', 'CREATE TABLE `chatbot_close_events` (\n  `close_id` int NOT NULL AUTO_INCREMENT,\n  `user_id` varchar(36) NOT NULL,\n  `session_id` varchar(36) DEFAULT NULL,\n  `closed_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `time_spent_seconds` int NOT NULL,\n  `last_user_message` text,\n  `last_bot_message` text,\n  PRIMARY KEY (`close_id`),\n  KEY `user_id` (`user_id`),\n  CONSTRAINT `chatbot_close_events_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)\n) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'


'conversations', 'CREATE TABLE `conversations` (\n  `conversation_id` varchar(36) NOT NULL,\n  `session_id` varchar(36) DEFAULT NULL,\n  `user_id` varchar(36) DEFAULT NULL,\n  `start_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `end_time` timestamp NULL DEFAULT NULL,\n  `duration` int DEFAULT \'0\',\n  `status` enum(\'active\',\'completed\',\'handover\',\'dropped\') DEFAULT \'active\',\n  `handover_reason` varchar(255) DEFAULT NULL,\n  `resolution_status` enum(\'resolved\',\'unresolved\',\'handover\') DEFAULT \'unresolved\',\n  PRIMARY KEY (`conversation_id`),\n  KEY `idx_session_id` (`session_id`),\n  KEY `idx_user_id` (`user_id`),\n  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`session_id`),\n  CONSTRAINT `conversations_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'


'conversations', 'CREATE TABLE `conversations` (\n  `conversation_id` varchar(36) NOT NULL,\n  `session_id` varchar(36) DEFAULT NULL,\n  `user_id` varchar(36) DEFAULT NULL,\n  `start_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `end_time` timestamp NULL DEFAULT NULL,\n  `duration` int DEFAULT \'0\',\n  `status` enum(\'active\',\'completed\',\'handover\',\'dropped\') DEFAULT \'active\',\n  `handover_reason` varchar(255) DEFAULT NULL,\n  `resolution_status` enum(\'resolved\',\'unresolved\',\'handover\') DEFAULT \'unresolved\',\n  PRIMARY KEY (`conversation_id`),\n  KEY `idx_session_id` (`session_id`),\n  KEY `idx_user_id` (`user_id`),\n  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`session_id`),\n  CONSTRAINT `conversations_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'


'conversations', 'CREATE TABLE `conversations` (\n  `conversation_id` varchar(36) NOT NULL,\n  `session_id` varchar(36) DEFAULT NULL,\n  `user_id` varchar(36) DEFAULT NULL,\n  `start_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,\n  `end_time` timestamp NULL DEFAULT NULL,\n  `duration` int DEFAULT \'0\',\n  `status` enum(\'active\',\'completed\',\'handover\',\'dropped\') DEFAULT \'active\',\n  `handover_reason` varchar(255) DEFAULT NULL,\n  `resolution_status` enum(\'resolved\',\'unresolved\',\'handover\') DEFAULT \'unresolved\',\n  PRIMARY KEY (`conversation_id`),\n  KEY `idx_session_id` (`session_id`),\n  KEY `idx_user_id` (`user_id`),\n  CONSTRAINT `conversations_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `sessions` (`session_id`),\n  CONSTRAINT `conversations_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci'
